Repository Decide-Full-Guadalfeo/Decide-Full-Guadalfeo-Votaciones, pull requests merged in 2021-01, with the labels that each got.

#35 fix: Arreglado bug de que se pueda parar una votación antes de empezarla
  decide/voting/admin.py
Labels: bug

#45 Fix/ganadoresprimarias terminado
  decide/voting/models.py
Labels: Prioridad Alta, bug

#47 test: He añadido una prueba de vista
  decide/voting/tests.py
Labels: Prioridad Media, bug

#58 fix: He arreglado el problema indiado en la issue y otros que he ido descubriendo
  decide/authentication/models.py
  decide/voting/models.py
Labels: Prioridad Alta, bug

#62 Fix/numpreguntas
  decide/voting/admin.py
  decide/voting/tests.py
Labels: Prioridad Alta, bug

#64 Feature/task009
  decide/voting/models.py
Labels: Prioridad Alta, feature

#66 fix: Arreglado el problema de división por 0
  decide/voting/models.py
Labels: Prioridad Alta, bug

#68 test: He añadido las 4 pruebas
  decide/voting/tests.py
Labels: Prioridad Media, feature

#80 fix: añadido selenium a requirements.txt
  requirements.txt
Labels: Prioridad Alta, bug, configuration

#88 feat: pruebas carga + API crear votacion general
  decide/voting/urls.py
  decide/voting/views.py
  loadtest/locustfile.py
Labels: help wanted

#98 Release/1.0.0
  .travis.yml
  Procfile
  README.md
  decide/authentication/admin.py
  decide/authentication/migrations/0001_initial.py
  decide/authentication/models.py
  decide/base/migrations/0001_initial.py
  decide/base/migrations/0002_auto_20180921_1056.py
  decide/base/migrations/0003_auto_20180921_1119.py
  decide/base/tests.py
  decide/census/migrations/0001_initial.py
  decide/decide/settings.py
  decide/decide/travis_settings.py
  decide/local_settings.py
  decide/mixnet/migrations/0001_initial.py
  decide/mixnet/migrations/0002_auto_20180216_1617.py
  decide/mixnet/migrations/0003_mixnet_auth_position.py
  decide/mixnet/migrations/0004_auto_20180605_0842.py
  decide/store/migrations/0001_initial.py
  decide/store/migrations/0002_vote_voted.py
  decide/store/migrations/0003_auto_20180921_1522.py
  decide/travis_local_settings.py
  decide/voting/admin.py
  decide/voting/migrations/0001_initial.py
  decide/voting/migrations/0002_auto_20180302_1100.py
  decide/voting/migrations/0003_auto_20180605_0842.py
  decide/voting/models.py
  decide/voting/serializers.py
  decide/voting/tests.py
  decide/voting/urls.py
  decide/voting/views.py
  docker/Dockerfile
  docker/docker-compose.yml
  docker/docker-settings.py
  loadtest/locustfile.py
  requirements.txt
  runtime.txt
Labels: Prioridad Alta

#102 Hotfix/1.0.0
  .travis.yml
  decide/decide/settings.py
  decide/decide/travis_settings.py
  decide/static/.keep
Labels: Prioridad Alta, bug

#107 Hotfix/1.0.0
  decide/decide/settings.py
  decide/decide/travis_settings.py
  decide/local_settings.py
Labels: Prioridad Alta, bug

#117 fix: He actualizado el método postproc y resuelto la incidencia
  decide/voting/models.py
Labels: Prioridad Alta, bug

#120 Se ha actualizado el método tally_votes
  decide/voting/models.py
Labels: Prioridad Alta, bug

#121 Release/1.2.0
  README.md
  decide/voting/models.py
  decide/voting/urls.py
  decide/voting/views.py
Labels: Prioridad Alta, bug

#125 fix: Arreglado el problema
  decide/voting/models.py
Labels: Prioridad Alta, bug

#124 Eliminada prueba duplicada
  decide/voting/tests.py
Labels: Prioridad Alta, bug
